// Game State
const GAME_STATE_WAITING = "GAME_STATE_WAITING";
const GAME_STATE_ACTIVE = "GAME_STATE_ACTIVE";
const GAME_STATE_GAME_OVER = "GAME_STATE_GAME_OVER";

// User roles
const USER_ROLE_GUEST = "USER_ROLE_GUEST";
const USER_ROLE_RED = "USER_ROLE_RED";
const USER_ROLE_YELLOW = "USER_ROLE_YELLOW";
const USER_ROLE_NONE = "USER_ROLE_NONE";
const USER_ROLES = {
  [USER_ROLE_GUEST]: "Guest",
  [USER_ROLE_RED]: "Red",
  [USER_ROLE_YELLOW]: "Yellow",
  [USER_ROLE_NONE]: "No one",
};

// URLs
const CLIENT_PORT = 3000;
const SERVER_PORT = 3001;
const CLIENT_URL = `http://localhost:${CLIENT_PORT}`;
const SERVER_URL = `http://localhost:${SERVER_PORT}`;

// Socket Events
const SOCKET_EVENT_JOIN_GAME = "SOCKET_EVENT_JOIN_GAME";
const SOCKET_EVENT_RESET_GAME = "SOCKET_EVENT_RESET_GAME";
const SOCKET_EVENT_MAKE_MOVE = "SOCKET_EVENT_MAKE_MOVE";
const SOCKET_EVENT_ASSIGN_ROLE = "SOCKET_EVENT_ASSIGN_ROLE";
const SOCKET_EVENT_UPDATE_STATE = "SOCKET_EVENT_UPDATE_STATE";
const SOCKET_EVENT_CONNECTION = "connection"; // Official socket event.
const SOCKET_EVENT_DISCONNECT = "disconnect"; // Official socket event.

// Must be CommonJS to accomodate for express server.
module.exports = {
  GAME_STATE_WAITING,
  GAME_STATE_ACTIVE,
  GAME_STATE_GAME_OVER,
  USER_ROLE_GUEST,
  USER_ROLE_RED,
  USER_ROLE_YELLOW,
  USER_ROLE_NONE,
  USER_ROLES,
  CLIENT_PORT,
  SERVER_PORT,
  CLIENT_URL,
  SERVER_URL,
  SOCKET_EVENT_JOIN_GAME,
  SOCKET_EVENT_RESET_GAME,
  SOCKET_EVENT_MAKE_MOVE,
  SOCKET_EVENT_ASSIGN_ROLE,
  SOCKET_EVENT_UPDATE_STATE,
  SOCKET_EVENT_CONNECTION,
  SOCKET_EVENT_DISCONNECT,
};
